- name: Copy docker.sh script to the remote server
  copy:
    src: ./docker.sh
    dest: /tmp/docker.sh
    mode: '0755'


- name: Run docker.sh script
  shell: sh /tmp/docker.sh
    
- name: Display operating system
  debug:
    msg: "Operating System is {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_version }}"


- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install awscli
  pip:
    name: awscli
    state: present


- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Debug docker_image_tag
  debug:
    var: docker_image_tag


- name: log in to Amazon ECRr
  shell: |
    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 426857564226.dkr.ecr.us-east-1.amazonaws.com/ghising-ecr
    

- name: Pull Docker image
  docker_image:
    name: "426857564226.dkr.ecr.us-east-1.amazonaws.com/ghising-ecr"
    tag: "7dbc20e6164b080e95aed0e99680ae9dcb721a7d-9894634009-1"
    # tag: "{{ docker_image_tag }}"
    source: pull


- name: Run Docker container
  docker_container:
    name: laravel_app
    image: "426857564226.dkr.ecr.us-east-1.amazonaws.com/ghising-ecr"
    state: started
    ports:
      - "9000:9000"
   





