- name: Copy docker.sh script to the remote server
  copy:
    src: ./docker.sh
    dest: /tmp/docker.sh
    mode: '0755'


- name: Run docker.sh script
  shell: sh /tmp/docker.sh
    
- name: Display operating system
  debug:
    msg: "Operating System is {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_version }}"


- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install awscli
  pip:
    name: awscli
    state: present


- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Pull Docker image
  docker_image:
    name: "{{ lookup('env', 'ECR_REGISTRY') }}/{{ lookup('env', 'ECR_REPOSITORY') }}"
    tag: latest
    source: pull

- name: Run Docker container
  docker_container:
    name: laravel_app
    image: "{{ lookup('env', 'ECR_REGISTRY') }}/{{ lookup('env', 'ECR_REPOSITORY') }}"
    state: started
    ports:
      - "9000:9000"
    env:
      DB_HOST: "{{ lookup('env', 'DB_HOST') }}"
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
      # BROADCAST_DRIVER: pusher
      # PUSHER_APP_ID: "{{ lookup('env', 'PUSHER_APP_ID') }}"
      # PUSHER_APP_KEY: "{{ lookup('env', 'PUSHER_APP_KEY') }}"
      # PUSHER_APP_SECRET: "{{ lookup('env', 'PUSHER_APP_SECRET') }}"
      # PUSHER_APP_CLUSTER: "{{ lookup('env', 'PUSHER_APP_CLUSTER') }}"





