- name: Copy docker.sh script to the remote server
  copy:
    src: ./docker.sh
    dest: /tmp/docker.sh
    mode: '0755'


- name: Run docker.sh script
  shell: sh /tmp/docker.sh
    
- name: Display operating system
  debug:
    msg: "Operating System is {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_version }}"


- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install awscli
  pip:
    name: awscli
    state: present



    

    